# Define the name of the workflow
name: API Integration Tests

# Specify the events that trigger the workflow
on: [push, pull_request]

# Define the jobs to be executed
jobs:
  # Define a job named "test"
  test:
    # Specify the runner environment
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      # Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Specify the version of Node.js to use
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install -g newman 

     # - name: Start the API server
        # Start the server in the background && wait 5 seconds for server to start
       # run: node index.js & sleep 5 
      - name: Start the API server
        run: |
          node index.js &
          sleep 5
          curl --retry 5 --retry-delay 5 -v http://localhost:3000/api/v1/status || exit 1

      # Run Postman tests using Newman
      - name: Run Postman tests with Newman
        run: newman run api_tests.postman_collection.json #Run Tests with Newman (CLI for Postman)
